# 基础配置
title: 机器学习教程
description: 交互式机器学习教程
baseurl: "/ml-tutorial" # 根据仓库名设置
url: "https://yourusername.github.io" # 你的GitHub Pages地址
theme: minima

# Markdown 解析设置
markdown: kramdown
kramdown:
  auto_ids: true
  header_offset: 1
  syntax_highlighter: rouge
  toc_levels: 1..3
  math_engine: mathjax

# 插件
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-relative-links

# 阅读器设置
reader:
  font_size: 18px
  default_theme: light

# 设置默认布局
defaults:
  - scope:
      path: ""
    values:
      layout: default
      show_sidebar: true