name: Update Directory JSON

permissions:
  contents: write

on:
  schedule:
    - cron: '*/5 * * * *'  # 每 5 分钟运行一次
  workflow_dispatch:  # 允许手动触发
  push:
    branches:
      - gh-pages  # 修改为触发的源分支

jobs:
  update-directory:
    runs-on: ubuntu-latest

    steps:
      # 步骤1：Checkout gh-pages 分支
      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages  # 拉取 gh-pages 分支以写入 directory.json

      # 步骤2：配置 Git
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # 步骤3：设置 Git 远程访问，使用 PAT Token
      - name: Set remote using PAT_TOKEN
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git

      # 步骤4：运行脚本来获取 GitHub 仓库目录结构并保存为 directory.json
      - name: Fetch GitHub directory structure
        run: |
          node fetch-directory.js  # 运行 Node.js 脚本来递归获取目录

      # 步骤5：提交并推送 directory.json 文件
      - name: Commit and push directory.json
        run: |
          git add directory.json
          git commit -m "Update directory JSON"
          git push origin gh-pages
