name: Update Directory JSON

permissions:
  contents: write

on:
  schedule:
    - cron: '*/5 * * * *'  # 每 5 分钟运行一次
  workflow_dispatch:  # 允许手动触发
  push:
    branches:
      - gh-pages  # 修改为触发的源分支，如果需要

jobs:
  update-directory:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages  # 拉取 gh-pages 分支以写入 directory.json

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Set remote using PAT_TOKEN
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Fetch GitHub directory structure
        run: |
          curl -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               "https://api.github.com/repos/${{ github.repository }}/contents?ref=gh-pages" \
               > directory.json

      - name: Commit and push directory.json
        run: |
          git add directory.json
          git commit -m "Update directory JSON"
          git push origin gh-pages
